# Generated by Django 5.1.3 on 2024-12-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_edi_user_data_temp_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='xlsx_file_path',
            field=models.FileField(blank=True, null=True, upload_to='csv_files/'),
        ),
    ]
