# Generated by Django 5.1.3 on 2024-12-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_files_xlsx_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='edi_segment_path',
            field=models.FileField(blank=True, null=True, upload_to='csv_files/'),
        ),
    ]
