# Generated by Django 5.1.3 on 2025-01-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_files_edi_segment_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_count', models.CharField(blank=True, max_length=255, null=True)),
                ('dependent_count', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('day', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
