# Generated by Django 5.0.12 on 2025-02-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_custodial_data_table_history_data_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dependent',
        ),
        migrations.DeleteModel(
            name='Eligibility',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
