# Generated by Django 5.0.12 on 2025-02-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_mssql_inventory_table_data_delete_dependent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count_model',
            old_name='dependent_count',
            new_name='other_dependent_count',
        ),
        migrations.AddField(
            model_name='count_model',
            name='spouse_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
