# Generated by Django 5.0.12 on 2025-02-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_rename_dependent_count_count_model_other_dependent_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mssql_count_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_count', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_count', models.CharField(blank=True, max_length=255, null=True)),
                ('other_dependent_count', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('day', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
