# Generated by Django 5.0.12 on 2025-02-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_mssql_count_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='recent_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('memeber_id', models.CharField(max_length=255, null=True)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('file_date', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
