# Generated by Django 5.0.12 on 2025-03-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_member_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeAddressTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_to_seq', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('address3', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('relationship', models.CharField(default='Member', max_length=50)),
                ('last_activity_date', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ssn', models.CharField(blank=True, max_length=20, null=True)),
                ('is_alternate_same', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp', models.CharField(max_length=255)),
                ('iF', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
