# Generated by Django 5.0.12 on 2025-03-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alternativeaddresstable_notesentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_table_data',
            name='term_date_last_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
