# Generated by Django 5.0.12 on 2025-04-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_inventory_table_data_term_date_last_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='sssn_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=255, null=True)),
                ('date', models.CharField(max_length=255, null=True)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('term_date', models.CharField(max_length=255, null=True)),
                ('member_id', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventory_table_data',
            name='reinstate_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory_table_data',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
