# Generated by Django 5.0.12 on 2025-06-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_sssn_logs_inventory_table_data_reinstate_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSN', models.CharField(max_length=20)),
                ('DPEFDY', models.CharField(max_length=4)),
                ('DPEFDM', models.CharField(max_length=2)),
                ('DPEFDD', models.CharField(max_length=2)),
            ],
        ),
    ]
